# Generated by Django 5.1.1 on 2024-10-02 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('annotation', models.TextField()),
                ('publication_year', models.IntegerField()),
                ('page_count', models.IntegerField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('publication_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publicationtype')),
            ],
        ),
    ]
