# Generated by Django 5.1.1 on 2024-10-03 10:34

import django.core.validators
import publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_publication_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', validators=[publications.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='page_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
